export const majorOptions = [
  { label: "Accounting", value: "accounting" },
  { label: "Anthropology", value: "anthropology" },
  { label: "Architecture", value: "architecture" },
  { label: "Art History", value: "art-history" },
  { label: "Biology", value: "biology" },
  { label: "Business Administration", value: "business-administration" },
  { label: "Chemical Engineering", value: "chemical-engineering" },
  { label: "Chemistry", value: "chemistry" },
  { label: "Civil Engineering", value: "civil-engineering" },
  { label: "Communications", value: "communications" },
  { label: "Computer Science", value: "computer-science" },
  { label: "Criminal Justice", value: "criminal-justice" },
  { label: "Economics", value: "economics" },
  { label: "Education", value: "education" },
  { label: "Electrical Engineering", value: "electrical-engineering" },
  { label: "English", value: "english" },
  { label: "Environmental Science", value: "environmental-science" },
  { label: "Finance", value: "finance" },
  { label: "Graphic Design", value: "graphic-design" },
  { label: "History", value: "history" },
  { label: "Information Technology", value: "information-technology" },
  { label: "International Relations", value: "international-relations" },
  { label: "Journalism", value: "journalism" },
  { label: "Marketing", value: "marketing" },
  { label: "Mathematics", value: "mathematics" },
  { label: "Mechanical Engineering", value: "mechanical-engineering" },
  { label: "Music", value: "music" },
  { label: "Nursing", value: "nursing" },
  { label: "Philosophy", value: "philosophy" },
  { label: "Physics", value: "physics" },
  { label: "Political Science", value: "political-science" },
  { label: "Psychology", value: "psychology" },
  { label: "Sociology", value: "sociology" },
  { label: "Theater and Drama", value: "theater-and-drama" },
]
