export const majorOptions = [
  "Accounting",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Science",
  "Criminal Justice",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "Graphic Design",
  "History",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology",
  "Theater and Drama",
]
